### ISSUE TITLE
Wrong folder name

### ISSUE THREAD

**Issue by robthecomputerguy** [tomslominski/yourls-redirect-index#1]
I had to read through your code to figure out that the exact name of the folder that needs to be put into /plugins/ is "redirect-index".

When downloaded from here, the folder is "yourls-redirect-index-master"

I don't know if you can/want to change the folder or the documentation, or something else but I wanted to let you know so you could fix it for the next person.

Aside from that though -- thanks so much for the plugin, I missed it the first few times I read through the list and it's so essential and common sense!

**Comment by tomslominski** [comment]
Thanks for reporting this. I didn't know it would fail if the plugin directory name wasn't `redirect-index` myself, but it looks like it does. I've fixed the documentation now to hopefully make it a bit clearer.

**Comment by hoochalaffa** [comment]
this issue helped me figure out what was going on. thanks.
