### ISSUE TITLE
All non https requests always redirect to the redirected index page

### ISSUE THREAD

**Issue by ftstp** [tomslominski/yourls-redirect-index#5]
Hi,

Since I activated https on yourls I have that issue:

All non https requests always redirect to the page linked by your plugin.
Can you help maybe? :)

My .htaccess is:

# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS
RewriteCond %{HTTPS} !=on

**Comment by tomslominski** [comment]
Hey, sorry for taking such a long time to look at this! I'm struggling to reproduce this on my end. Do you mean that even valid short URLs, that redirect correctly if using HTTPS, redirect to the page set in settings using HTTP? Can you post your .htaccess between triple backtics (```) so it actually outputs as code please? Also, can you post your shortener's URL?

**Comment by ftstp** [comment]
No problem tom!
Yes that was the exact problem but since few days I don't have that error anymore, I may have tweaked something in the htaccess to fix it so it's all good now :) 


Here is at this time:
```
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS
RewriteCond %{HTTPS} !=on
```

Thanks anyway, your plugin is great!
Best

**Comment by tomslominski** [comment]
Brilliant, thank you 🙂 I will close the issue.
