### ISSUE TITLE
"The URL is the same as what you tried to change it to"

### ISSUE THREAD

**Issue by tobidwest** [tomslominski/yourls-redirect-index#8]
The plug-in shows this error when trying to change the URL, all though this is **not** the case.
`The URL is the same as what you tried to change it to, so it has been kept.`

**Comment by tomslominski** [comment]
What URL are you changing from and to?

**Comment by tobidwest** [comment]
I was trying to change it from empty to
blog.herderzeitung.de/?utm_source=hz_shorturl_home.

>

**Comment by tomslominski** [comment]
Try adding https:// at the start of the URL. If that doesn't help, what browser & OS are you on?

**Comment by tobidwest** [comment]
This does not solve it. Chrome / Windows 10.

**Comment by tomslominski** [comment]
I see. And when you go back to the page after clicking save and getting the error (select it from the menu rather than just refreshing the page), is the field still empty?

**Comment by tobidwest** [comment]
I just repeated clicking "Save" a few times and it seemed to work this
time. I think this issue can be closed. Thank you for your support anyway :)
