### ISSUE TITLE
only working if logged in 

### ISSUE THREAD

**Issue by luxpatrick** [tomslominski/yourls-redirect-index#9]
only working if logged in, what could cause this?

**Comment by tomslominski** [comment]
Not sure - I've not seen that before. Have you copied the index.php file from the plugin directory to the root of your YOURLS installation?

**Comment by luxpatrick** [comment]
I think so....
<img width="817" alt="Bildschirmfoto 2020-12-23 um 19 18 52" src="https://user-images.githubusercontent.com/48523191/103026313-eb775300-4553-11eb-82b6-ec8abc100f1f.png">

**Comment by luxpatrick** [comment]
I have tested it, it's only working in the browser logged in. Are there any recommendations in case of permissions or anything else?

**Comment by tomslominski** [comment]
Hmm, I’m a bit stumped to be honest with you! What happens when the browser doesn’t redirect, do you just get an empty page? What is the URL of your YOURLS installation (feel free to email me it at tom@slomin.ski if you don’t want to post it on here)?

**Comment by luxpatrick** [comment]
Yes, just a blank. Page. It’s on lux.jetzt
We now fixed it in the htaccess

**Comment by tomslominski** [comment]
Sorry I wasn’t able to be more help, but I’m glad you got there in the end!

**Comment by justinmarty** [comment]
I had the same issue, but discovered it was a conflict with a YOURLS theme (https://sleeky.flynntes.com/).
